<?php

// in config/fbref_schemas.php
return [
    // =================================================================
    // Schema per i Portieri ('P')
    // Usato da fbref:scrape-player per pagine giocatore singolo (Portieri)
    // Contiene solo le tabelle e i campi rilevanti per i portieri.
    // =================================================================
    
    'P' => [
        // La tabella 'scout_summary_GK' ha una struttura differente
        // con 'data-stat' sulle intestazioni di riga (<th>), non sulle celle <td> dei valori.
        // Il metodo parseTableWithDataStat() come modificato non la estrarrà automaticamente.
        // Se questi dati sono necessari, richiederà una logica di parsing specifica.
        // 'scout_summary_GK'=>[],
        
        'stats_keeper_dom_lg' => [ // Corrisponde a 'Goalkeeping: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            'MP' => 'gk_games',
            'Starts' => 'gk_games_starts',
            'Min' => 'gk_minutes',
            '90s' => 'minutes_90s',
            'GA' => 'gk_goals_against',
            'GA90' => 'gk_goals_against_per90',
            'SoTA' => 'gk_shots_on_target_against',
            'Saves' => 'gk_saves',
            'Save%' => 'gk_save_pct',
            'W' => 'gk_wins',
            'D' => 'gk_ties',
            'L' => 'gk_losses',
            'CS' => 'gk_clean_sheets',
            'CS%' => 'gk_clean_sheets_pct',
            'PKatt' => 'gk_pens_att',
            'PKA' => 'gk_pens_allowed',
            'PKsv' => 'gk_penalties_saved',
            'PKm' => 'gk_pens_missed',
            'Save%_PK' => 'gk_pens_save_pct',
        ],
        'stats_keeper_adv_dom_lg' => [ // Corrisponde a 'Advanced Goalkeeping: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            '90s' => 'minutes_90s',
            'GA' => 'gk_goals_against',
            'PKA' => 'gk_pens_allowed',
            'FK_GA' => 'gk_free_kick_goals_against',
            'CK_GA' => 'gk_corner_kick_goals_against',
            'OG_GA' => 'gk_own_goals_against',
            'PSxG' => 'gk_psxg',
            'PSxG/SoT' => 'gk_psnpxg_per_shot_on_target_against',
            'PSxG_Net' => 'gk_psxg_net',
            'PSxG_Net/90' => 'gk_psxg_net_per90',
            'Cmp_Launched' => 'gk_passes_completed_launched',
            'Att_Launched' => 'gk_passes_launched',
            'Cmp%_Launched' => 'gk_passes_pct_launched',
            'Att_GK_Pass' => 'gk_passes',
            'Thr' => 'gk_passes_throws',
            'Launch%_Pass' => 'gk_pct_passes_launched',
            'AvgLen_Pass' => 'gk_passes_length_avg',
            'Att_GoalKicks' => 'gk_goal_kicks',
            'Launch%_GoalKicks' => 'gk_pct_goal_kicks_launched',
            'AvgLen_GoalKicks' => 'gk_goal_kick_length_avg',
            'Crosses_Faced' => 'gk_crosses',
            'Crosses_Stopped' => 'gk_crosses_stopped',
            'Crosses_Stopped%' => 'gk_crosses_stopped_pct',
            '#OPA' => 'gk_def_actions_outside_pen_area',
            '#OPA/90' => 'gk_def_actions_outside_pen_area_per90',
            'AvgDist_DefActions' => 'gk_avg_distance_def_actions',
        ],
    ],
    
    // =================================================================
    // SCHEMA per i Giocatori di Campo (Difensori, Centrocampisti, Attaccanti)
    // Questo schema può essere considerato il tuo schema per 'D'.
    // Usato da fbref:scrape-player per pagine giocatore singolo (Giocatori di Movimento)
    // =================================================================
    'player_field_stats' => [
        'stats_standard_dom_lg' => [ // Corrisponde a 'Standard Stats: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            'MP' => 'games',
            'Starts' => 'games_starts',
            'Min' => 'minutes',
            '90s' => 'minutes_90s',
            'Gls' => 'goals',
            'Ast' => 'assists',
            'G+A' => 'goals_assists',
            'G-PK' => 'goals_pens',
            'PK' => 'pens_made',
            'PKatt' => 'pens_att',
            'CrdY' => 'cards_yellow',
            'CrdR' => 'cards_red',
            'xG' => 'xg',
            'npxG' => 'npxg',
            'xAG' => 'xg_assist',
            'npxG+xAG' => 'npxg_xg_assist',
            'PrgC' => 'progressive_carries',
            'PrgP' => 'progressive_passes',
            'PrgR' => 'progressive_passes_received',
            'Gls/90' => 'goals_per90',
            'Ast/90' => 'assists_per90',
            'G+A/90' => 'goals_assists_per90',
            'G-PK/90' => 'goals_pens_per90',
            'G+A-PK/90' => 'goals_assists_pens_per90',
            'xG/90' => 'xg_per90',
            'xAG/90' => 'xg_assist_per90',
            'xG+xAG/90' => 'xg_xg_assist_per90',
            'npxG/90' => 'npxg_per90',
            'npxG+xAG/90' => 'npxg_xg_assist_per90',
        ],
        'stats_shooting_dom_lg' => [ // Corrisponde a 'Shooting: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            '90s' => 'minutes_90s',
            'Gls' => 'goals',
            'Sh' => 'shots',
            'SoT' => 'shots_on_target',
            'SoT%' => 'shots_on_target_pct',
            'Sh/90' => 'shots_per90',
            'SoT/90' => 'shots_on_target_per90',
            'G/Sh' => 'goals_per_shot',
            'G/SoT' => 'goals_per_shot_on_target',
            'Dist' => 'average_shot_distance',
            'FK' => 'shots_free_kicks',
            'PK' => 'pens_made',
            'PKatt' => 'pens_att',
            'xG' => 'xg',
            'npxG' => 'npxg',
            'npxG/Sh' => 'npxg_per_shot',
            'G-xG' => 'xg_net',
            'np:G-xG' => 'npxg_net',
        ],
        'stats_passing_dom_lg' => [ // Corrisponde a 'Passing: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            '90s' => 'minutes_90s',
            'Cmp' => 'passes_completed',
            'Att' => 'passes',
            'Cmp%' => 'passes_pct',
            'TotDist' => 'passes_total_distance',
            'PrgDist' => 'passes_progressive_distance',
            'Cmp_Short' => 'passes_completed_short',
            'Att_Short' => 'passes_short',
            'Cmp%_Short' => 'passes_pct_short',
            'Cmp_Medium' => 'passes_completed_medium',
            'Att_Medium' => 'passes_medium',
            'Cmp%_Medium' => 'passes_pct_medium',
            'Cmp_Long' => 'passes_completed_long',
            'Att_Long' => 'passes_long',
            'Cmp%_Long' => 'passes_pct_long',
            'Ast' => 'assists',
            'xAG' => 'xg_assist',
            'xA' => 'pass_xa',
            'A-xAG' => 'xg_assist_net',
            'KP' => 'assisted_shots',
            '1/3' => 'passes_into_final_third',
            'PPA' => 'passes_into_penalty_area',
            'CrsPA' => 'crosses_into_penalty_area',
            'PrgP' => 'progressive_passes',
        ],
        'stats_passing_types_dom_lg' => [ // Corrisponde a 'Pass Types: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            '90s' => 'minutes_90s',
            'Att' => 'passes',
            'Live' => 'passes_live',
            'Dead' => 'passes_dead',
            'FK' => 'passes_free_kicks',
            'TB' => 'through_balls',
            'Sw' => 'passes_switches',
            'Crs' => 'crosses',
            'TI' => 'throw_ins',
            'CK' => 'corner_kicks',
            'In' => 'corner_kicks_in',
            'Out' => 'corner_kicks_out',
            'Str' => 'corner_kicks_straight',
            'Cmp' => 'passes_completed',
            'Off' => 'passes_offsides',
            'Blocks' => 'passes_blocked',
        ],
        'stats_gca_dom_lg' => [ // Corrisponde a 'Goal and Shot Creation: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            '90s' => 'minutes_90s',
            'SCA' => 'sca',
            'SCA90' => 'sca_per90',
            'PassLive_SCA' => 'sca_passes_live',
            'PassDead_SCA' => 'sca_passes_dead',
            'TO_SCA' => 'sca_take_ons',
            'Sh_SCA' => 'sca_shots',
            'Fld_SCA' => 'sca_fouled',
            'Def_SCA' => 'sca_defense',
            'GCA' => 'gca',
            'GCA90' => 'gca_per90',
            'PassLive_GCA' => 'gca_passes_live',
            'PassDead_GCA' => 'gca_passes_dead',
            'TO_GCA' => 'gca_take_ons',
            'Sh_GCA' => 'gca_shots',
            'Fld_GCA' => 'gca_fouled',
            'Def_GCA' => 'gca_defense',
        ],
        'stats_defense_dom_lg' => [ // Corrisponde a 'Defensive Actions: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            '90s' => 'minutes_90s',
            'Tkl' => 'tackles',
            'TklW' => 'tackles_won',
            'Def 3rd' => 'tackles_def_3rd',
            'Mid 3rd' => 'tackles_mid_3rd',
            'Att 3rd' => 'tackles_att_3rd',
            'Tkl_Dribblers' => 'challenge_tackles',
            'Att_Dribbles' => 'challenges',
            'Tkl%_Dribblers' => 'challenge_tackles_pct',
            'Lost_Dribbles' => 'challenges_lost',
            'Blocks' => 'blocks',
            'Sh_Blocks' => 'blocked_shots',
            'Pass_Blocks' => 'blocked_passes',
            'Int' => 'interceptions',
            'Tkl+Int' => 'tackles_interceptions',
            'Clr' => 'clearances',
            'Err' => 'errors',
        ],
        'stats_possession_dom_lg' => [ // Corrisponde a 'Possession: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            '90s' => 'minutes_90s',
            'Touches' => 'touches',
            'Def Pen' => 'touches_def_pen_area',
            'Def 3rd' => 'touches_def_3rd',
            'Mid 3rd' => 'touches_mid_3rd',
            'Att 3rd' => 'touches_att_3rd',
            'Att Pen' => 'touches_att_pen_area',
            'Live_Ball_Touches' => 'touches_live_ball',
            'Att_TakeOns' => 'take_ons',
            'Succ_TakeOns' => 'take_ons_won',
            'Succ%_TakeOns' => 'take_ons_won_pct',
            'Tkld_TakeOns' => 'take_ons_tackled',
            'Tkld%_TakeOns' => 'take_ons_tackled_pct',
            'Carries' => 'carries',
            'TotDist_Carries' => 'carries_distance',
            'PrgDist_Carries' => 'carries_progressive_distance',
            'PrgC' => 'progressive_carries',
            '1/3_Carries' => 'carries_into_final_third',
            'CPA' => 'carries_into_penalty_area',
            'Mis' => 'miscontrols',
            'Dis' => 'dispossessed',
            'Rec' => 'passes_received',
            'PrgR' => 'progressive_passes_received',
        ],
        'stats_playing_time_dom_lg' => [ // Corrisponde a 'Playing Time: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            'MP' => 'games',
            'Min' => 'minutes',
            'Min/MP' => 'minutes_per_game',
            'Min%' => 'minutes_pct',
            '90s' => 'minutes_90s',
            'Starts' => 'games_starts',
            'Mn/Start' => 'minutes_per_start',
            'Compl' => 'games_complete',
            'Subs' => 'games_subs',
            'Mn/Sub' => 'minutes_per_sub',
            'unSub' => 'unused_subs',
            'PPM' => 'points_per_game',
            'onG' => 'on_goals_for',
            'onGA' => 'on_goals_against',
            '+/-' => 'plus_minus',
            '+/-90' => 'plus_minus_per90',
            'On-Off_PM' => 'plus_minus_wowy',
            'onxG' => 'on_xg_for',
            'onxGA' => 'on_xg_against',
            'xG+/-' => 'xg_plus_minus',
            'xG+/-90' => 'xg_plus_minus_per90',
            'On-Off_xG' => 'xg_plus_minus_wowy',
        ],
        'stats_misc_dom_lg' => [ // Corrisponde a 'Miscellaneous Stats: Domestic Leagues'
            'Season' => 'year_id',
            'Age' => 'age',
            'Squad' => 'team',
            'Country' => 'country',
            'Comp' => 'comp_level',
            'LgRank' => 'lg_finish',
            '90s' => 'minutes_90s',
            'CrdY' => 'cards_yellow',
            'CrdR' => 'cards_red',
            '2CrdY' => 'cards_yellow_red',
            'Fls' => 'fouls',
            'Fld' => 'fouled',
            'Off' => 'offsides',
            'Crs' => 'crosses',
            'Int' => 'interceptions',
            'TklW' => 'tackles_won',
            'PKwon' => 'pens_won',
            'PKcon' => 'pens_conceded',
            'OG' => 'own_goals',
            'Recov' => 'ball_recoveries',
            'Won_Aerials' => 'aerials_won',
            'Lost_Aerials' => 'aerials_lost',
            'Won%_Aerials' => 'aerials_won_pct',
        ],
    ],
    // =================================================================
    // NUOVO SCHEMA: team_player_stats (Resta invariato)
    // Usato da fbref:scrape-team per mappare i dati da tutte le tabelle squadra
    // =================================================================
    'team_player_stats' => [
        // Chiave pulita: 'stats_standard'
        'stats_standard' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Pos' => 'position',
            'Età' => 'age',
            'MP' => 'games',
            'Starts' => 'games_starts',
            'Min' => 'minutes',
            '90s' => 'minutes_90s',
            'Gls' => 'goals',
            'Ast' => 'assists',
            'G+A' => 'goals_assists',
            'G-PK' => 'goals_pens',
            'PK' => 'pens_made',
            'PKatt' => 'pens_att',
            'CrdY' => 'cards_yellow',
            'CrdR' => 'cards_red',
            'xG' => 'xg',
            'npxG' => 'npxg',
            'xAG' => 'xg_assist',
            'npxG+xAG' => 'npxg_xg_assist',
            'PrgC' => 'progressive_carries',
            'PrgP' => 'progressive_passes',
            'PrgR' => 'progressive_passes_received',
        ],
        
        // Chiave pulita: 'stats_keeper'
        'stats_keeper' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Età' => 'age',
            'MP' => 'gk_games',
            'Starts' => 'gk_games_starts',
            'Min' => 'gk_minutes',
            '90s' => 'minutes_90s',
            'GA' => 'gk_goals_against',
            'GA90' => 'gk_goals_against_per90',
            'SoTA' => 'gk_shots_on_target_against',
            'Saves' => 'gk_saves',
            'Save%' => 'gk_save_pct',
            'W' => 'gk_wins',
            'D' => 'gk_ties',
            'L' => 'gk_losses',
            'CS' => 'gk_clean_sheets',
            'CS%' => 'gk_clean_sheets_pct',
            'PKatt' => 'gk_pens_att',
            'PKA' => 'gk_pens_allowed',
            'PKsv' => 'gk_pens_saved',
            'PKm' => 'gk_pens_missed',
            'Save%_1' => 'gk_pens_save_pct',
        ],
        //'stats_keeper_adv'=>[],
        
        // Chiave pulita: 'stats_shooting'
        'stats_shooting' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Età' => 'age',
            '90s' => 'minutes_90s',
            'Sh' => 'shots',
            'SoT' => 'shots_on_target',
            'SoT%' => 'shots_on_target_pct',
            'Sh/90' => 'shots_per90',
            'SoT/90' => 'shots_on_target_per90',
            'G/Sh' => 'goals_per_shot',
            'G/SoT' => 'goals_per_shot_on_target',
            'Dist' => 'average_shot_distance',
            'FK' => 'shots_free_kicks',
            'npxG/Sh' => 'npxg_per_shot',
            'G-xG' => 'xg_net',
            'np:G-xG' => 'npxg_net',
        ],
        
        // Chiave pulita: 'stats_passing'
        'stats_passing' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Età' => 'age',
            '90s' => 'minutes_90s',
            'Cmp' => 'passes_completed',
            'Att' => 'passes',
            'Cmp%' => 'passes_pct',
            'TotDist' => 'passes_total_distance',
            'PrgDist' => 'passes_progressive_distance',
            'Cmp_1' => 'passes_completed_short',
            'Att_1' => 'passes_short',
            'Cmp%_1' => 'passes_pct_short',
            'Cmp_2' => 'passes_completed_medium',
            'Att_2' => 'passes_medium',
            'Cmp%_2' => 'passes_pct_medium',
            'Cmp_3' => 'passes_completed_long',
            'Att_3' => 'passes_long',
            'Cmp%_3' => 'passes_pct_long',
            'Ast' => 'assists',
            'xAG' => 'xg_assist',
            'xA' => 'pass_xa',
            'A-xAG' => 'xg_assist_net',
            'KP' => 'assisted_shots',
            '1/3' => 'passes_into_final_third',
            'PPA' => 'passes_into_penalty_area',
            'CrsPA' => 'crosses_into_penalty_area',
            'PrgP' => 'progressive_passes',
        ],
        'stats_playing_time'=>[],
        // Chiave pulita: 'stats_passing_types'
        'stats_passing_types' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Età' => 'age',
            '90s' => 'minutes_90s',
            'Live' => 'passes_live',
            'Dead' => 'passes_dead',
            'FK' => 'passes_free_kicks',
            'TB' => 'through_balls',
            'Sw' => 'passes_switches',
            'Crs' => 'crosses',
            'TI' => 'throw_ins',
            'CK' => 'corner_kicks',
            'In' => 'corner_kicks_in',
            'Out' => 'corner_kicks_out',
            'Str' => 'corner_kicks_straight',
            'Off' => 'passes_offsides',
            'Blocks' => 'passes_blocked',
        ],
        
        // Chiave pulita: 'stats_gca'
        'stats_gca' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Età' => 'age',
            '90s' => 'minutes_90s',
            'SCA' => 'sca',
            'SCA90' => 'sca_per90',
            'PassLive' => 'sca_passes_live',
            'PassDead' => 'sca_passes_dead',
            'TO' => 'sca_take_ons',
            'Sh' => 'sca_shots',
            'Fld' => 'sca_fouled',
            'Def' => 'sca_defense',
            'GCA' => 'gca',
            'GCA90' => 'gca_per90',
            'PassLive_1' => 'gca_passes_live',
            'PassDead_1' => 'gca_passes_dead',
            'TO_1' => 'gca_take_ons',
            'Sh_1' => 'gca_shots',
            'Fld_1' => 'gca_fouled',
            'Def_1' => 'gca_defense',
        ],
        
        // Chiave pulita: 'stats_defense'
        'stats_defense' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Età' => 'age',
            '90s' => 'minutes_90s',
            'Tkl' => 'tackles',
            'TklW' => 'tackles_won',
            'Def 3rd' => 'tackles_def_3rd',
            'Mid 3rd' => 'tackles_mid_3rd',
            'Att 3rd' => 'tackles_att_3rd',
            'Tkl_1' => 'challenge_tackles',
            'Att' => 'challenges',
            'Tkl%' => 'challenge_tackles_pct',
            'Lost' => 'challenges_lost',
            'Blocks' => 'blocks',
            'Sh' => 'blocked_shots',
            'Pass' => 'blocked_passes',
            'Int' => 'interceptions',
            'Tkl+Int' => 'tackles_interceptions',
            'Clr' => 'clearances',
            'Err' => 'errors',
        ],
        
        // Chiave pulita: 'stats_possession'
        'stats_possession' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Età' => 'age',
            '90s' => 'minutes_90s',
            'Touches' => 'touches',
            'Def Pen' => 'touches_def_pen_area',
            'Def 3rd' => 'touches_def_3rd',
            'Mid 3rd' => 'touches_mid_3rd',
            'Att 3rd' => 'touches_att_3rd',
            'Att Pen' => 'touches_att_pen_area',
            'Live' => 'touches_live_ball',
            'Att_1' => 'take_ons',
            'Succ' => 'take_ons_won',
            'Succ%' => 'take_ons_won_pct',
            'Tkld' => 'take_ons_tackled',
            'Tkld%' => 'take_ons_tackled_pct',
            'Carries' => 'carries',
            'TotDist' => 'carries_distance',
            'PrgDist' => 'carries_progressive_distance',
            'PrgC' => 'progressive_carries',
            '1/3' => 'carries_into_final_third',
            'CPA' => 'carries_into_penalty_area',
            'Mis' => 'miscontrols',
            'Dis' => 'dispossessed',
            'Rec' => 'passes_received',
            'PrgR' => 'progressive_passes_received',
        ],
        
        // Chiave pulita: 'stats_misc'
        'stats_misc' => [
            'Giocatore' => 'Player',
            'Naz' => 'nationality',
            'Età' => 'age',
            '90s' => 'minutes_90s',
            'CrdY' => 'cards_yellow',
            'CrdR' => 'cards_red',
            '2CrdY' => 'cards_yellow_red',
            'Fls' => 'fouls',
            'Fld' => 'fouled',
            'Off' => 'offsides',
            'Crs' => 'crosses',
            'Int' => 'interceptions',
            'TklW' => 'tackles_won',
            'PKwon' => 'pens_won',
            'PKcon' => 'pens_conceded',
            'OG' => 'own_goals',
            'Recov' => 'ball_recoveries',
            'Won' => 'aerials_won',
            'Lost' => 'aerials_lost',
            'Won%' => 'aerials_won_pct',
        ],
    ]
];